//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatalyaYakovenko.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ActivityJury = new HashSet<ActivityJury>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IDMeet { get; set; }
        public int Day_Number { get; set; }
        public System.TimeSpan Time_Start { get; set; }
        public int ModeratorID { get; set; }
    
        public virtual Meet Meet { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityJury> ActivityJury { get; set; }
    }
}
