

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NatalyaYakovenko.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class YakovenkoEntities : DbContext
{
    public YakovenkoEntities()
        : base("name=YakovenkoEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Activity> Activity { get; set; }

    public virtual DbSet<ActivityJury> ActivityJury { get; set; }

    public virtual DbSet<City> City { get; set; }

    public virtual DbSet<Country> Country { get; set; }

    public virtual DbSet<Direction> Direction { get; set; }

    public virtual DbSet<Event> Event { get; set; }

    public virtual DbSet<Gender> Gender { get; set; }

    public virtual DbSet<Meet> Meet { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

