//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatalyaYakovenko.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Activity = new HashSet<Activity>();
            this.ActivityJury = new HashSet<ActivityJury>();
            this.Meet = new HashSet<Meet>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int IDGender { get; set; }
        public string E_mail { get; set; }
        public System.DateTime Date_birthday { get; set; }
        public int IDCountry { get; set; }
        public string Number_Phone { get; set; }
        public Nullable<int> IDDirection { get; set; }
        public string Password { get; set; }
        public Nullable<int> IDEvent { get; set; }
        public int IDRole { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityJury> ActivityJury { get; set; }
        public virtual Country Country { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Event Event { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meet> Meet { get; set; }
        public virtual Role Role { get; set; }
    }
}
